### ISSUE TITLE
RSS reader includes a Lumina RSS entry that doesn't work

### ISSUE THREAD

**Issue by possnfiffer** [lumina-desktop/lumina#565]
The RSS reader that comes with Lumina includes an RSS link (http://lumina-desktop.org/?feed=rss2) that isn't producing any output in the RSS reader. I added a new RSS feed using this link (https://lumina-desktop.org/feed/) and it works great.

**Comment by possnfiffer** [comment]
![screenshot-2018-04-10-15-09-08](https://user-images.githubusercontent.com/773239/38583812-708adbe0-3cd1-11e8-82ad-27ee1f04a790.png)
![screenshot-2018-04-10-15-10-10](https://user-images.githubusercontent.com/773239/38583813-70a341da-3cd1-11e8-856f-c18b2abafd09.png)

**Comment by possnfiffer** [comment]
uname -a output:

FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by beanpole135** [comment]
This has already been fixed in the latest sources (1.4.2)
The HTTP -> HTTPS redirect was just not getting noticed properly, and the RSS reader now detects/follows the redirects as needed.

**Comment by possnfiffer** [comment]
This is still an issue. I'm at SCaLE 17x and using FreeBSD-12-RELEASE to teach the Getting Started with FreeBSD workshop where we're using Lumina in the workshop and when we first get Lumina installed there's a big empty widget in the corner with the wrong RSS feed for the Lumina website. You say this is fixed in the latest sources (1.4.2) Even today, I'm only able to install Lumina 1.4.1. There are people here at the conference using FreeBSD-13 and even they are only able to install Lumina 1.4.1 so they also run into this issue. When will Lumina 1.4.2 be available with the fix?

**Comment by beanpole135** [comment]
Lumina 1.4.2 has been available in the source tree for months now - that is independant of the version of FreeBSD you are using.

**Comment by possnfiffer** [comment]
So JT is the maintainer, does he just need to update the port?

**Comment by beanpole135** [comment]
That would be my guess. Or you could just checkout the lumina repo and run "qmake ; make ; sudo make install"
